apiVersion: v1
kind: Pod
metadata:
  name: sample-annotations
  annotations:
    description: "This is a sample pod"
    foo: "123"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
